import type { BuildKind } from "./types";

type Palette = { ink: string; accent: string; secondary: string; paper: string; glow: string };

const palettes: Palette[] = [
  { ink: "#15202b", accent: "#ff6b35", secondary: "#12b8a6", paper: "#f4f0e8", glow: "#f2c94c" },
  { ink: "#201a2d", accent: "#8b7cff", secondary: "#22c7a9", paper: "#f7f3ec", glow: "#ff8c69" },
  { ink: "#17232b", accent: "#f0b429", secondary: "#e85d75", paper: "#f5f0e7", glow: "#57c7b3" },
  { ink: "#1b2630", accent: "#2979ff", secondary: "#ff5c8a", paper: "#f2f1eb", glow: "#a4d65e" },
];

function choosePalette(prompt: string): Palette {
  const score = [...prompt].reduce((sum, character) => sum + character.charCodeAt(0), 0);
  return palettes[score % palettes.length];
}

function safeText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function scriptValue(value: string): string {
  return JSON.stringify(safeText(value)).replace(/</g, "\\u003c");
}

function documentShell(title: string, body: string, script: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeText(title)}</title><style>*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#101820;color:#f4f0e8}body{padding:18px}button,input{font:inherit}button{cursor:pointer;border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.08);color:inherit;padding:9px 13px;border-radius:9px}button:hover{background:rgba(255,255,255,.16)}button:focus-visible,input:focus-visible{outline:2px solid #f2c94c;outline-offset:3px}.shell{max-width:900px;margin:auto}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:14px}.eyebrow{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:#a8b3bd}.title{font-size:clamp(20px,4vw,34px);line-height:1.05;margin:5px 0 0;max-width:720px}.prompt{font-size:12px;line-height:1.5;color:#b9c4cc;max-width:650px;margin:9px 0 0}.stage{border:1px solid rgba(255,255,255,.16);background:#17232d;border-radius:16px;overflow:hidden;box-shadow:0 20px 70px rgba(0,0,0,.28)}.controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:12px;border-bottom:1px solid rgba(255,255,255,.12);font-size:12px}.controls label{display:flex;align-items:center;gap:8px}.controls input{accent-color:#ff6b35}.readout{padding:12px 15px;border-top:1px solid rgba(255,255,255,.12);font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;color:#c8d2d8}.status{color:#9be3cf}@media (max-width:600px){body{padding:10px}.top{display:block}.controls{margin-top:10px}}</style></head><body><main class="shell"><header class="top"><div><div class="eyebrow">Prompt Forge / executable artifact</div><h1 class="title">${safeText(title)}</h1><p class="prompt">${safeText("This artifact was compiled from the visitor's prompt and runs in a restricted preview frame.")}</p></div><button id="reset" type="button">Reset</button></header><section class="stage">${body}</section><div class="readout"><span class="status">● runtime online</span><span id="readout"> ready</span></div></main><script>${script}</script></body></html>`;
}

function svgArtifact(title: string, prompt: string, palette: Palette): string {
  const body = `<div class="controls"><label>Energy <input id="energy" type="range" min="12" max="96" value="62"></label><button id="pulse" type="button">Run pulse</button><button id="phase" type="button">Flip phase</button></div><svg id="diagram" viewBox="0 0 900 520" role="img" aria-label="Interactive prompt signal diagram" style="display:block;width:100%;height:auto;min-height:360px"><defs><linearGradient id="g" x1="0" x2="1"><stop offset="0" stop-color="${palette.secondary}"/><stop offset="1" stop-color="${palette.accent}"/></linearGradient><filter id="blur"><feGaussianBlur stdDeviation="18"/></filter></defs><rect width="900" height="520" fill="#17232d"/><circle id="halo" cx="450" cy="260" r="142" fill="${palette.accent}" opacity=".16" filter="url(#blur)"/><circle id="core" cx="450" cy="260" r="82" fill="url(#g)"/><circle cx="450" cy="260" r="30" fill="${palette.glow}"/><g id="rings" fill="none" stroke="${palette.glow}" stroke-width="2" opacity=".65"><ellipse cx="450" cy="260" rx="180" ry="70"/><ellipse cx="450" cy="260" rx="260" ry="112" transform="rotate(-18 450 260)"/><ellipse cx="450" cy="260" rx="340" ry="148" transform="rotate(28 450 260)"/></g><g id="nodes"></g><path id="trace" fill="none" stroke="${palette.secondary}" stroke-width="4" stroke-linecap="round"/></svg>`;
  const script = `const prompt=${scriptValue(prompt)};const palette=${JSON.stringify(palette)};let phase=0,energy=62,ticks=0;const readout=document.getElementById('readout');const nodes=document.getElementById('nodes');const diagram=document.getElementById('diagram');const trace=document.getElementById('trace');const energyInput=document.getElementById('energy');const core=document.getElementById('core');const halo=document.getElementById('halo');function draw(){phase+=0.018*(0.5+energy/100);ticks+=1;const radius=70+energy*0.6;core.setAttribute('r',String(radius));halo.setAttribute('r',String(radius+55));nodes.innerHTML='';let path='';for(let i=0;i<8;i++){const a=phase+i*Math.PI/4;const x=450+Math.cos(a)*(180+energy*0.7);const y=260+Math.sin(a)*(115+energy*0.38);nodes.innerHTML+='<circle cx="'+x.toFixed(1)+'" cy="'+y.toFixed(1)+'" r="7" fill="'+palette.glow+'" opacity=".9"/>';path+=(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)+' '}trace.setAttribute('d',path);readout.textContent=' energy '+energy+'% · frame '+ticks+' · '+prompt.slice(0,34)}draw();const timer=setInterval(draw,60);energyInput.addEventListener('input',()=>{energy=Number(energyInput.value)});document.getElementById('pulse').addEventListener('click',()=>{energy=Math.min(96,energy+12);energyInput.value=String(energy)});document.getElementById('phase').addEventListener('click',()=>{phase+=Math.PI});document.getElementById('reset').addEventListener('click',()=>{phase=0;energy=62;energyInput.value='62'});window.__forgeTelemetry={getState:()=>({energy,phase,ticks}),reset:()=>{phase=0;energy=62}};`;
  return documentShell(title, body, script);
}

function arcadeArtifact(title: string, prompt: string, palette: Palette): string {
  const body = `<div class="controls"><button id="start" type="button">Start run</button><button id="reset" type="button">Reset</button><span>Move: WASD / arrows · collect the bright cells</span></div><canvas id="game" width="900" height="500" aria-label="Playable canvas game"></canvas>`;
  const script = `const prompt=${scriptValue(prompt)};const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const keys=new Set();let player={x:70,y:390,vx:0,vy:0};let enemies=[];let gems=[];let score=0;let running=false;let elapsed=0;let last=performance.now();const palette=${JSON.stringify(palette)};function reset(){player={x:70,y:390,vx:0,vy:0};enemies=[];gems=[];score=0;elapsed=0;running=false;for(let i=0;i<5;i++)gems.push({x:140+i*145,y:90+(i%2)*55});for(let i=0;i<4;i++)enemies.push({x:650-(i%2)*100,y:70+i*75,speed:55+i*11});}function start(){running=true;reset();running=true}function keyName(e){return e.key.toLowerCase()}window.addEventListener('keydown',e=>{keys.add(keyName(e));if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(keyName(e)))e.preventDefault()});window.addEventListener('keyup',e=>keys.delete(keyName(e)));document.getElementById('start').addEventListener('click',start);document.getElementById('reset').addEventListener('click',()=>{reset();running=false});function update(dt){if(!running)return;const vx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);const vy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);player.x=Math.max(24,Math.min(876,player.x+vx*250*dt));player.y=Math.max(24,Math.min(476,player.y+vy*250*dt));elapsed+=dt;for(const enemy of enemies){enemy.y+=enemy.speed*dt;if(enemy.y>490)enemy.y=20}for(const gem of gems){if(!gem.taken&&Math.hypot(gem.x-player.x,gem.y-player.y)<28){gem.taken=true;score+=100;readout.textContent=' score '+score+' · '+prompt.slice(0,28)}}}function draw(){ctx.fillStyle='#17232d';ctx.fillRect(0,0,900,500);ctx.strokeStyle='rgba(255,255,255,.07)';for(let x=0;x<900;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,500);ctx.stroke()}for(let y=0;y<500;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke()}ctx.fillStyle=palette.accent;ctx.beginPath();ctx.arc(player.x,player.y,17,0,Math.PI*2);ctx.fill();ctx.fillStyle=palette.glow;for(const gem of gems)if(!gem.taken){ctx.beginPath();ctx.arc(gem.x,gem.y,10,0,Math.PI*2);ctx.fill()}ctx.fillStyle=palette.secondary;for(const enemy of enemies){ctx.fillRect(enemy.x-12,enemy.y-12,24,24)}ctx.fillStyle='#f4f0e8';ctx.font='16px ui-monospace,monospace';ctx.fillText(running?'RUNNING':'READY · press start',22,30);ctx.fillText('SCORE '+score,760,30);ctx.fillText('TIME '+elapsed.toFixed(1),760,54)}function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}const readout=document.getElementById('readout');reset();draw();requestAnimationFrame(frame);window.__forgeTelemetry={getState:()=>({score,elapsed,running,player:{x:player.x,y:player.y}}),reset,start};`;
  return documentShell(title, body, script);
}

function orbitArtifact(title: string, prompt: string, palette: Palette): string {
  const body = `<div class="controls"><button id="spin" type="button">Change orbit</button><button id="reset" type="button">Reset camera</button><span>Drag to orbit · scroll to zoom</span></div><div id="space" style="height:500px;background:#080d14"></div>`;
  void body;
  const script = `import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';const prompt=${scriptValue(prompt)};const host=document.getElementById('space');const scene=new THREE.Scene();scene.background=new THREE.Color('#080d14');const camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,100);camera.position.set(0,2.3,6.5);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const palette=${JSON.stringify(palette)};scene.add(new THREE.HemisphereLight('#dbeafe','#101820',2.1));const star=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:palette.glow,size:.035}));const positions=new Float32Array(1200*3);for(let i=0;i<1200;i++){positions[i*3]=(Math.random()-.5)*12;positions[i*3+1]=(Math.random()-.5)*8;positions[i*3+2]=(Math.random()-.5)*10}star.geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));scene.add(star);const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,2),new THREE.MeshStandardMaterial({color:palette.accent,roughness:.34,metalness:.18,emissive:palette.accent,emissiveIntensity:.16}));scene.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.018,12,128),new THREE.MeshBasicMaterial({color:palette.secondary}));ring.rotation.x=Math.PI/2.4;scene.add(ring);const moon=new THREE.Mesh(new THREE.SphereGeometry(.23,24,24),new THREE.MeshStandardMaterial({color:palette.glow,roughness:.7}));scene.add(moon);let angle=.7;let spin=1;const readout=document.getElementById('readout');document.getElementById('spin').addEventListener('click',()=>{spin*=-1});document.getElementById('reset').addEventListener('click',()=>{camera.position.set(0,2.3,6.5);controls.target.set(0,0,0);angle=.7;spin=1});function resize(){camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)}window.addEventListener('resize',resize);function frame(){requestAnimationFrame(frame);angle+=0.008*spin;moon.position.set(Math.cos(angle)*2.1,Math.sin(angle*1.8)*.55,Math.sin(angle)*2.1);core.rotation.x+=.006;core.rotation.y+=.009;ring.rotation.z+=.003;controls.update();readout.textContent=' orbital phase '+angle.toFixed(2)+' · '+prompt.slice(0,30);renderer.render(scene,camera)}frame();window.__forgeTelemetry={getState:()=>({angle,spin,coreRotation:core.rotation.y}),reset:()=>{angle=.7;spin=1}};`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${safeText(title)}</title><style>*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#080d14;color:#f4f0e8}body{padding:18px}.shell{max-width:900px;margin:auto}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:14px}.eyebrow{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:#a8b3bd}.title{font-size:clamp(20px,4vw,34px);line-height:1.05;margin:5px 0 0;max-width:720px}.prompt{font-size:12px;line-height:1.5;color:#b9c4cc;max-width:650px;margin:9px 0 0}.stage{border:1px solid rgba(255,255,255,.16);background:#101820;border-radius:16px;overflow:hidden;box-shadow:0 20px 70px rgba(0,0,0,.28)}.controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:12px;border-bottom:1px solid rgba(255,255,255,.12);font-size:12px}.controls span{color:#a8b3bd}.readout{padding:12px 15px;border-top:1px solid rgba(255,255,255,.12);font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;color:#c8d2d8}.status{color:#9be3cf}button{cursor:pointer;border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.08);color:inherit;padding:9px 13px;border-radius:9px}button:hover{background:rgba(255,255,255,.16)}button:focus-visible{outline:2px solid #f2c94c;outline-offset:3px}@media (max-width:600px){body{padding:10px}.top{display:block}.controls{margin-top:10px}}</style><script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"}}</script></head><body><main class="shell"><header class="top"><div><div class="eyebrow">Prompt Forge / Three.js artifact</div><h1 class="title">${safeText(title)}</h1><p class="prompt">${safeText("A spatial study compiled from the prompt. Drag the scene to inspect it.")}</p></div><button id="resetTop" type="button">Reset</button></header><section class="stage"><div class="controls"><button id="spin" type="button">Change orbit</button><button id="reset" type="button">Reset camera</button><span>Drag to orbit · scroll to zoom</span></div><div id="space" style="height:500px;background:#080d14"></div></section><div class="readout"><span class="status">● runtime online</span><span id="readout"> ready</span></div></main><script type="module">${script.replace("document.getElementById('reset')", "document.getElementById('resetTop')")}</script></body></html>`;
}

function climateArtifact(title: string, prompt: string, palette: Palette): string {
  const body = `<div class="controls"><label>Temperature <input id="temp" type="range" min="-2" max="10" value="2"></label><label>Forest <input id="forest" type="range" min="0" max="100" value="54"></label><label>Energy <input id="energy" type="range" min="0" max="100" value="38"></label><button id="pulse" type="button">Project 10 years</button></div><svg id="earth" viewBox="0 0 900 520" role="img" aria-label="Interactive climate simulation" style="display:block;width:100%;height:auto;min-height:360px"><defs><radialGradient id="ocean"><stop offset="0" stop-color="#52c7c0"/><stop offset="1" stop-color="#174a71"/></radialGradient><filter id="soft"><feGaussianBlur stdDeviation="16"/></filter></defs><rect width="900" height="520" fill="#16222c"/><circle id="globe" cx="450" cy="260" r="150" fill="url(#ocean)"/><path id="land" d="M330 205c35-45 78-26 97-4 25-8 53 18 45 48-16 14-42 7-50 31-25 12-44-20-69-7-25-16-37-43-23-68Z" fill="#8ecf76" opacity=".95"/><path id="land2" d="M475 290c30-18 66 6 62 39-20 30-54 26-73 5-14-15-8-35 11-44Z" fill="#b5dc75" opacity=".9"/><ellipse id="smog" cx="450" cy="260" rx="185" ry="70" fill="#ff8c69" opacity=".12" filter="url(#soft)"/><g id="rings" fill="none" stroke="#f2c94c" opacity=".55"><ellipse cx="450" cy="260" rx="210" ry="80"/><ellipse cx="450" cy="260" rx="270" ry="118" transform="rotate(-16 450 260)"/></g><text x="450" y="454" text-anchor="middle" fill="#f4f0e8" font-size="18" font-family="ui-monospace,monospace">PROJECTION / 10 YEARS</text></svg>`;
  const script = `const prompt=${scriptValue(prompt)};const palette=${JSON.stringify(palette)};let temp=2,forest=54,energy=38,years=0;const readout=document.getElementById('readout');const globe=document.getElementById('globe');const smog=document.getElementById('smog');const land=document.getElementById('land');const land2=document.getElementById('land2');function update(){const vitality=Math.max(0,Math.min(100,100-Math.max(0,temp-4)*8+(forest-50)*.4+energy*.25));globe.setAttribute('fill',vitality>60?'url(#ocean)':vitality>30?'#477d87':'#6d4e64');smog.setAttribute('opacity',String(Math.max(0,.04+(temp-2)*.025)));land.setAttribute('opacity',String(Math.max(.18,forest/100)));land2.setAttribute('opacity',String(Math.max(.12,(forest-10)/100)));readout.textContent=' vitality '+Math.round(vitality)+' · year '+years+' · '+prompt.slice(0,28)}[['temp','t'],['forest','f'],['energy','e']].forEach(([id,key])=>document.getElementById(id).addEventListener('input',event=>{if(key==='t')temp=Number(event.target.value);if(key==='f')forest=Number(event.target.value);if(key==='e')energy=Number(event.target.value);update()}));document.getElementById('pulse').addEventListener('click',()=>{years+=10;temp=Math.min(10,temp+(energy<30?2:1));forest=Math.max(0,forest-(temp>6?7:3));update()});document.getElementById('reset').addEventListener('click',()=>{temp=2;forest=54;energy=38;years=0;document.getElementById('temp').value='2';document.getElementById('forest').value='54';document.getElementById('energy').value='38';update()});update();window.__forgeTelemetry={getState:()=>({temp,forest,energy,years}),reset:()=>{temp=2;forest=54;energy=38;years=0;update()}};`;
  return documentShell(title, body, script);
}

export function compileArtifact(kind: BuildKind, prompt: string, title: string): { code: string; mode: "iframe"; summary: string } {
  const palette = choosePalette(prompt);
  if (kind === "arcade") return { code: arcadeArtifact(title, prompt, palette), mode: "iframe", summary: "A keyboard-and-touch canvas game with a real score loop." };
  if (kind === "orbit") return { code: orbitArtifact(title, prompt, palette), mode: "iframe", summary: "A Three.js spatial study with camera controls and runtime telemetry." };
  if (kind === "climate") return { code: climateArtifact(title, prompt, palette), mode: "iframe", summary: "A parameter-driven climate projection with live SVG state." };
  return { code: svgArtifact(title, prompt, palette), mode: "iframe", summary: "An interactive SVG signal diagram with controls and live telemetry." };
}
