import type { Build, EngineResult, SourceRecord } from "./types";

function factorLine(label: string, value: number, contribution: number): string {
  return `- ${label}: ${value}/100 (${contribution} points)`;
}

export function renderBuildMarkdown(build: Build, sources: SourceRecord[], analysis?: EngineResult): string {
  const sourceLines = sources.length > 0
    ? sources.map((source) => `- [${source.title}](${source.url}) — ${source.publisher}, ${source.date}`).join("\n")
    : "- No external sources attached.";
  const result = analysis ?? { score: build.score, recommendation: build.recommendation, factors: build.factors };
  return `# ${build.title}\n\n${build.prompt}\n\n## Artifact\n\n- Kind: ${build.kind}\n- Preview: sandboxed ${build.previewMode}\n- Version: ${build.version}\n- Seal: ${build.seal}\n\n## Forge analysis\n\n- Score: ${result.score}/100\n- Recommendation: ${result.recommendation}\n${result.factors.map((factor) => factorLine(factor.label, factor.value, factor.contribution)).join("\n")}\n\n## Provenance\n\n${sourceLines}\n\n## Run it\n\nOpen the build detail page and use the rendered preview. The artifact is generated by the deterministic compiler; it is not a claim that the upstream prompt will always produce the same result.\n\nGenerated by Prompt Forge.\n`;
}
