import { compileArtifact } from "./artifact";
import { sealEvent } from "./canonical";
import { analyzePrompt } from "./engine";
import type { Build, SourceRecord } from "./types";

export const sourceCatalog: SourceRecord[] = [
  {
    id: "openai-astra-official",
    title: "GPT-6 Astra: a new generation of intelligence",
    publisher: "OpenAI",
    kind: "official",
    url: "https://openai.com/index/gpt-6-astra/",
    date: "2026-09-03",
    excerpt: "OpenAI describes Astra as a model for computer use, browsing, software engineering, and long-running work.",
    model: "GPT-6 Astra",
    tags: ["agent", "coding", "computer-use"],
    artifactHint: "Agent console and browser-game workflow",
  },
  {
    id: "anthropic-opus-official",
    title: "Introducing Claude Opus 5.5",
    publisher: "Anthropic",
    kind: "official",
    url: "https://www.anthropic.com/claude-opus-5-5",
    date: "2026-09-22",
    excerpt: "Anthropic positions Opus 5.5 for long-running agentic coding, computer use, and knowledge work.",
    model: "Claude Opus 5.5",
    tags: ["agent", "coding", "long-horizon"],
    artifactHint: "Long-horizon build loop with visible checkpoints",
  },
  {
    id: "linkedin-peter-yang-games",
    title: "Four games built with Astra, Blender, and Godot",
    publisher: "Peter Yang on LinkedIn",
    kind: "social",
    url: "https://www.linkedin.com/posts/petergyang_gpt-6-astra-4-amazing-games-you-can-build-activity-7502040691649228801-HOge",
    date: "2026-09-05",
    excerpt: "A public build diary covering a space shooter, moving-train FPS, strategy level, and deck builder.",
    model: "GPT-6 Astra",
    tags: ["games", "3d", "workflow"],
    artifactHint: "A playable loop beats a static screenshot",
  },
  {
    id: "linkedin-demos-caveat",
    title: "One prompt is marketing; sixty prompts are a game",
    publisher: "Brantley Brumley II on LinkedIn",
    kind: "social",
    url: "https://www.linkedin.com/posts/brantley-brumley-ii_b972b9138_ai-unity-buildinpublic-activity-7502025845042122752-jR2d",
    date: "2026-09-05",
    excerpt: "A counterpoint argues that assets, iteration, playtesting, and taste still matter more than a one-shot prompt.",
    model: "GPT-6 Astra",
    tags: ["games", "critique", "iteration"],
    artifactHint: "Runtime telemetry and revision history",
  },
  {
    id: "dev-space-simulator",
    title: "How I built a 3D space simulator in one day with Claude",
    publisher: "DEV Community",
    kind: "article",
    url: "https://dev.to/yusufktkoglu/how-i-built-a-3d-space-simulator-in-one-day-with-claude-threejs-shaders-42b",
    date: "2026-04-23",
    excerpt: "A single-file Three.js simulator uses procedural textures, shaders, and iterative prompt constraints.",
    model: "Claude",
    tags: ["threejs", "simulation", "svg"],
    artifactHint: "Procedural visuals without an asset pipeline",
  },
  {
    id: "github-worldbuild-bench",
    title: "WorldBuild Bench: playable 3D games from one brief",
    publisher: "sebnado",
    kind: "benchmark",
    url: "https://github.com/sebnado/worldbuild-bench",
    date: "2026-07-01",
    excerpt: "A fixed harness compares browser-playable 3D builds with playability and world-coherence checks.",
    model: "Multiple",
    tags: ["benchmark", "playtesting", "threejs"],
    artifactHint: "A fixed scaffold makes model comparisons inspectable",
  },
  {
    id: "github-threejs-starter",
    title: "Three.js game starter pack with prompt files",
    publisher: "heagandev",
    kind: "repository",
    url: "https://github.com/heagandev/threejs-agent-starter",
    date: "2026-05-02",
    excerpt: "A playable starter pairs a real game loop with reusable Three.js references and staged prompts.",
    model: "Agent-agnostic",
    tags: ["games", "threejs", "skills"],
    artifactHint: "A working first build before feature expansion",
  },
  {
    id: "github-prompt-tripo",
    title: "Prompt-to-Tripo game asset upgrade",
    publisher: "chaoyubai8-tech",
    kind: "repository",
    url: "https://github.com/chaoyubai8-tech/prompt-to-tripo-game",
    date: "2026-08-28",
    excerpt: "A post-processing layer upgrades placeholder meshes while preserving the original game loop.",
    model: "GPT-5.5 / Codex",
    tags: ["3d", "assets", "postprocess"],
    artifactHint: "Separate the playable core from asset polish",
  },
  {
    id: "dev-elsewhere",
    title: "Elsewhere: a text-to-3D studio",
    publisher: "DEV Community",
    kind: "article",
    url: "https://dev.to/rawr/elsewhere-a-text-to-3d-studio-3bif",
    date: "2026-03-04",
    excerpt: "A constrained JSON scene schema is compiled into a Three.js scene instead of trusting raw executable code.",
    model: "Gemini",
    tags: ["3d", "schema", "compiler"],
    artifactHint: "Validate a scene spec before rendering it",
  },
  {
    id: "github-noobi",
    title: "Noobi.ai: prompt to reviewed playable game",
    publisher: "Innate-Labs",
    kind: "repository",
    url: "https://github.com/Innate-Labs/Noobi.ai",
    date: "2026-09-25",
    excerpt: "A local-first agent turns a prompt into a reviewed browser game rather than a static prototype.",
    model: "Agent-agnostic",
    tags: ["games", "review", "local-first"],
    artifactHint: "A review gate belongs in the creation loop",
  },
];

function makeSeedBuild(id: string, title: string, prompt: string, kind: Build["kind"], sourceIds: string[], createdAt: string): Build {
  const artifact = compileArtifact(kind, prompt, title);
  const analysis = analyzePrompt(prompt, kind, sourceIds);
  const payload = { id, title, prompt, kind, sourceIds, artifactCode: artifact.code, score: analysis.score, factors: analysis.factors };
  const seal = sealEvent("", payload);
  return {
    id,
    title,
    prompt,
    kind,
    status: "published",
    sourceIds,
    artifactCode: artifact.code,
    previewMode: "iframe",
    score: analysis.score,
    recommendation: analysis.recommendation,
    factors: analysis.factors,
    createdAt,
    updatedAt: createdAt,
    version: 1,
    prevSeal: "",
    seal,
    ownerScope: "public-seed",
  };
}

export const seedBuilds: Build[] = [
  makeSeedBuild(
    "seed-astra-orbit",
    "Astra Orbit Lab",
    "Build a calm, interactive SVG-like orbital study with a glowing core, draggable camera, a reset control, and a visible phase readout. Make it feel like a small instrument rather than a dashboard.",
    "orbit",
    ["openai-astra-official", "github-worldbuild-bench"],
    "2026-09-24T10:00:00.000Z",
  ),
  makeSeedBuild(
    "seed-tidal-arcade",
    "Tidal Rush Arcade",
    "Create a playable browser arcade loop where the player collects bright cells, avoids moving hazards, and can reset the run. Use keyboard and touch controls and show score and elapsed time in the artifact.",
    "arcade",
    ["linkedin-peter-yang-games", "github-threejs-starter"],
    "2026-09-23T10:00:00.000Z",
  ),
  makeSeedBuild(
    "seed-earth-sim",
    "Earth Condition Simulator",
    "Create an interactive climate projection with temperature, forest, and clean-energy sliders. Show a changing Earth, a ten-year projection button, and a vitality readout without claiming scientific precision.",
    "climate",
    ["dev-space-simulator", "dev-elsewhere"],
    "2026-09-22T10:00:00.000Z",
  ),
  makeSeedBuild(
    "seed-signal-svg",
    "Prompt Signal SVG",
    "Make a standalone interactive SVG signal diagram with a pulse button, energy slider, phase toggle, and a readout that proves the runtime is changing state.",
    "svg",
    ["openai-astra-official", "anthropic-opus-official", "linkedin-demos-caveat"],
    "2026-09-21T10:00:00.000Z",
  ),
];
