import Link from "next/link";
import { ArrowRight, Play, Sparkles } from "lucide-react";
import { Reveal } from "@/components/reveal";
import { BuildCard } from "@/components/build-card";
import { FeedClient } from "@/components/feed-client";
import { listBuilds } from "@/lib/db";
import { getSourceCatalog } from "@/lib/db";

export default async function Home() {
  const builds = await listBuilds("public-seed");
  const sources = getSourceCatalog();
  return <div className="page-wrap">
    <section className="hero"><div><div className="eyebrow-row"><span className="micro-label">Prompt Forge / public artifact lab</span><span className="form-hint">Research → compile → play</span></div><h1>Prompts in.<br /><em>Runnable things</em> out.</h1><p className="hero-copy">A research-backed workbench for turning the web&apos;s best AI coding prompts into inspectable SVG instruments, browser games, 3D studies, and simulations you can actually use.</p><div className="hero-actions"><Link className="primary-button" href="/build">Compile a prompt <ArrowRight size={16} /></Link><Link className="secondary-button" href="/library">Browse the library <Play size={15} /></Link></div></div><div className="hero-board"><span className="board-label">The loop / 04 moves</span><h2>See the prompt become a thing.</h2><div className="board-flow"><div><span>01 · source record</span><b>PROVENANCE</b></div><div><span>02 · deterministic brief</span><b>ENGINE</b></div><div><span>03 · sandboxed artifact</span><b>RENDER</b></div><div><span>04 · revision + export</span><b>SEALED</b></div></div><div className="board-stamp">PLAY<br />THE<br />OUTPUT</div></div></section>
    <section className="stat-row"><div className="stat-cell"><strong>{sources.length}</strong><span>source records</span></div><div className="stat-cell"><strong>{builds.length}</strong><span>seeded artifacts</span></div><div className="stat-cell"><strong>04</strong><span>render families</span></div><div className="stat-cell"><strong>0</strong><span>required API keys</span></div></section>
    <section className="section-block"><div className="section-heading"><div><span className="micro-label">The useful loop</span><h2>Not a prompt wall.<br />A workbench.</h2></div><p>Every record keeps the original idea, the evidence attached to it, the runtime result, and the revision that changed it.</p></div><div className="jobs-grid"><Reveal className="job-card"><span className="job-number">01 / DISCOVER</span><h3>Start with a real creation.</h3><p>Browse public examples from model launches, developer posts, repositories, and benchmark harnesses.</p></Reveal><Reveal className="job-card" delay={.08}><span className="job-number">02 / COMPILE</span><h3>Make the brief executable.</h3><p>Choose a render family, attach sources, and get a safe iframe with controls, telemetry, and a real reset path.</p></Reveal><Reveal className="job-card" delay={.16}><span className="job-number">03 / CARRY</span><h3>Leave something useful.</h3><p>Revise the build, replay its hash chain, and export a Markdown report with provenance and an honest score.</p></Reveal></div></section>
    <section className="section-block"><div className="section-heading"><div><span className="micro-label">Featured artifacts</span><h2>Open one. Break it.</h2></div><Link className="text-button" href="/library">See all artifacts <ArrowRight size={14} /></Link></div><div className="build-grid">{builds.slice(0, 4).map((build, index) => <Reveal key={build.id} delay={index * .05}><BuildCard build={build} featured={index === 0} /></Reveal>)}</div></section>
    <section className="section-block"><div className="section-heading"><div><span className="micro-label">Live research shelf</span><h2>Follow the signal,<br />not the hype.</h2></div><p>GitHub and DEV results are normalized into the same shape. When providers fail, the fallback is labeled instead of pretending to be live.</p></div><FeedClient /></section>
    <section className="section-block"><div className="section-heading"><div><span className="micro-label">Build in public</span><h2>Make the next one<br />worth sharing.</h2></div><Link className="primary-button" href="/build">Open the composer <Sparkles size={15} /></Link></div></section>
  </div>;
}
